### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Jondeboy** [gabriel-oana/wotreplay#2]
Im getting index error when doing the following: 
replay = ReplayData(file_path='some_replay.wotreplay', db_path='', db_name='', load=False)

File "C:\Python38\lib\site-packages\wotreplay\wotreplay.py", line 14, in __init__
    self.battle_performance = self.replay.get_battle_performance()
  File "C:\Python38\lib\site-packages\wotreplay\action\extract_data_from_replay.py", line 97, in get_battle_performance
    performance = Extractor.get_battle_performance(data=self.battle_data, account_id=self.account_id,
  File "C:\Python38\lib\site-packages\wotreplay\helper\extractor.py", line 86, in get_battle_performance
    raw_data = data[0]['personal']
IndexError: list index out of range

[some_replay.zip](https://github.com/gabriel-oana/wotreplay/files/9946118/some_replay.zip)

**Comment by gabriel-oana** [comment]
I'll have a look at this soon.

**Comment by gabriel-oana** [comment]
@Jondeboy I have found the problem and will make a fix for it and deploy a new version soon. There are few things that can be improved here and will address that too. 
Thanks for raising this issue

**Comment by Jondeboy** [comment]
No problem, thanks for the quick reply!

**Comment by gabriel-oana** [comment]
@Jondeboy I have pushed a minor fix in place. 
This will however not fix your issue because your replay is incomplete. 

When you play a battle but go back to garage before the battle is over, the replay does not capture any information about what has happened in the battle. 
It will only capture some information that is set before the battle such as the map and your tank and some information about your opponents but not the results. 

You can re-install the package "1.0.3" and it will raise an error when the replay you try to parse is incomplete.

**Comment by Jondeboy** [comment]
Thank you! I will try the latest version this week. Im using your library because Im interested in my average winrate for each map.

I feel like other maps I have around 70% winrate and other 50%. This would help me to improve my strategy for maps with bad winrate.

**Comment by Jondeboy** [comment]
Did you mean I can re-install package 1.0.2? I cant find 1.0.3.

**Comment by gabriel-oana** [comment]
Yes sorry my bad. It's version 1.0.2 not 1.0.3.

**Comment by Jondeboy** [comment]
This works now as expected. Thank you for the fix!
